# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13KSR0uxjE_3a0gcGg4Dloe5iVc91cCbS
"""

import re


def tampilkan_menu():
    """Menampilkan menu utama ke pengguna."""
    print("\n" + "="*30)
    print("      MENU APLIKASI DATA")
    print("="*30)
    print("1. Tampilkan Data (Diurutkan A-Z)")
    print("2. Tampilkan Data (Diurutkan Z-A)")
    print("3. Tampilkan Data Tidak Cocok")
    print("4. Cari Nama")
    print("5. Keluar")
    print("-"*30)

def tampilkan_data_terurut(combined_data, reverse_sort=False):
    """Menampilkan data gabungan yang sudah diurutkan."""

    combined_data.sort(reverse=reverse_sort)

    if reverse_sort:
        print("\n--- Data Gabungan (Diurutkan Z-A berdasarkan Nama) ---")
    else:
        print("\n--- Data Gabungan (Diurutkan A-Z berdasarkan Nama) ---")

    if not combined_data:
        print("Belum ada data gabungan.")
        return

    for name, location in combined_data:
        print(f"- {name} - {location}")

def tampilkan_data_tidak_cocok(unmatched_names, unmatched_locations):
    """Menampilkan nama atau lokasi yang tidak punya pasangan."""
    print("\n--- Laporan Data Tidak Cocok ---")

    ada_data_tidak_cocok = False

    if unmatched_names:
        print("\nNama tanpa pasangan daerah:")
        for name in unmatched_names:
            print(f"- {name}")
        ada_data_tidak_cocok = True

    if unmatched_locations:
        print("\nDaerah tanpa pasangan nama:")
        for location in unmatched_locations:
            print(f"- {location}")
        ada_data_tidak_cocok = True

    if not ada_data_tidak_cocok:
        print("✅ Semua data memiliki pasangan.")

def cari_data(combined_data, unmatched_names):
    """Mencari nama dalam data gabungan dan data tidak cocok."""

    print("\n--- Pencarian Nama ---")
    search_query = input("Masukkan nama yang ingin dicari: ").strip()

    if search_query:
        search_query_lower = search_query.lower()

        found_in_combined = []
        found_in_unmatched = []

        for name, location in combined_data:
            if search_query_lower in name.lower():
                found_in_combined.append((name, location))

        for name in unmatched_names:
            if search_query_lower in name.lower():
                found_in_unmatched.append(name)

        if found_in_combined or found_in_unmatched:
            print(f"\n✅ Ditemukan hasil untuk '{search_query}':")

            if found_in_combined:
                print("\nDi data gabungan (nama & daerah):")
                for name, location in found_in_combined:
                    print(f"  - {name} - {location}")

            if found_in_unmatched:
                print("\nDi nama tanpa pasangan:")
                for name in found_in_unmatched:
                    print(f"  - {name}")
        else:
            print(f"\n❌ Nama '{search_query}' tidak ditemukan.")
    else:
        print("Pencarian dibatalkan (tidak ada nama yang dimasukkan).")


def main():
    """Fungsi utama untuk menjalankan aplikasi."""

    print("--- Setup Awal Program ---")
    print("Masukkan nama-nama (pisahkan dengan koma jika lebih dari satu, contoh: 'Budi, Ani, Cahya'):")
    names_input = input()
    print("Masukkan daerah-daerah (pisahkan dengan koma jika lebih dari satu, contoh: 'Jakarta, Surabaya, Bandung'):")
    locations_input = input()

    names = [name.strip() for name in re.split(r',\s*', names_input) if name.strip()]
    locations = [location.strip() for location in re.split(r',\s*', locations_input) if location.strip()]

    combined_data = list(zip(names, locations))
    unmatched_names = []
    unmatched_locations = []

    if len(names) > len(locations):
        unmatched_names = names[len(locations):]
    elif len(locations) > len(names):
        unmatched_locations = locations[len(names):]

    print("\nData awal berhasil diproses. Masuk ke menu utama.")

    while True:
        tampilkan_menu()
        pilihan = input("Masukkan pilihan (1-5): ").strip()

        if pilihan == '1':

            tampilkan_data_terurut(combined_data, reverse_sort=False)

        elif pilihan == '2':

            tampilkan_data_terurut(combined_data, reverse_sort=True)

        elif pilihan == '3':

            tampilkan_data_tidak_cocok(unmatched_names, unmatched_locations)

        elif pilihan == '4':

            cari_data(combined_data, unmatched_names)

        elif pilihan == '5':

            print("\nTerima kasih telah menggunakan program ini. Sampai jumpa!")
            break

        else:
            print(f"\n❌ Pilihan '{pilihan}' tidak valid. Silakan pilih 1, 2, 3, 4, atau 5.")

if __name__ == "__main__":
    main()